version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      # Menggunakan konfigurasi tanpa password seperti default Laragon/XAMPP teman Anda
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: guardwatch_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Auto-import sql file
      - ./guardwatch_db_utf8.sql:/docker-entrypoint-initdb.d/guardwatch_db.sql

  api-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=guardwatch_db
      - PORT=3000
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    env_file:
      - ./backend/.env
    depends_on:
      - mysql-db

  web-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api-server

volumes:
  db_data:
